### ISSUE TITLE
meta-analysis blog post

### ISSUE THREAD

**Issue by softloud** [ggupta2/matcha_codejam#4]
for Canadian pdoc application

example from Charles' job application

- [ ] choose a dataset from `metafor::` (meta-analysis package) 
- [ ] recreate the analysis
- [ ] explain to oneself what is happening
- [ ] interpret the results
- [ ] `browseVignettes("metafor")`

**Comment by softloud** [comment]
And create a blog to put it on

options 
- `distill::` - for science
- `blogdown::` - most conventional
- `hugodown::` - in development but better than blogdown in some ways
- `pkgdown::`- for packages

## set up blog

Go through Chapter 1; it ends with a recommend workflow for setting up a blog. 

- [ ] create the blog
- [ ] create the post
- [ ] deploy on github pages

**Comment by softloud** [comment]
Note the "vignettes" for `metafor::` are in the **massive** pdf on the package. Not friendly to find. But if you can bear drilling in to find one example, just focus on that, recreating the code.

Another option is to look for someone else blog post on meta-analysis and recreate that.

**Comment by softloud** [comment]
Another tip. Look for data that has control & treatment continuous measures, mean and sd. Easiest to do a standardised mean difference meta-analysis.

**Comment by softloud** [comment]
In particular three functions from `metafor::` are of interest:

1. `::escalc` for calculating the effect and the variance of the effect (odds-ratio, risk-ratio, standardised mean difference) 
2. `::rma` for random effects meta-analysis, i.e., the modelling function
3.  `::forest` for plotting the forest plot
